version: '3.6'
services:
  web:
    build: .
    volumes:
      - .:/app
      - ./docker_dir/sample_password.yml:/app/tmp/env_config/sample_password.yml
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: "mysql:5.7"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anzard
      MYSQL_USER: anzard
      MYSQL_PASSWORD: anzard
    volumes:
      - .:/app
      - "./docker_dir/db:/var/lib/mysql"
      - "./docker_dir/prepare_anzard_mysql_user.sql:/docker-entrypoint-initdb.d/prepare_anzard_mysql_user.sql"
    ports:
      - "3306:3306"
